-- Create the Users table
CREATE TABLE Users (
    UserID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	Country VARCHAR(40) NOT NULL,
    ProfilePicture VARBINARY(MAX)
);

-- Create the Contacts table
CREATE TABLE Contacts (
    ContactID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    UserID UNIQUEIDENTIFIER NOT NULL,
    ContactUserID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (ContactUserID) REFERENCES Users(UserID)
);

-- Create the Messages table
CREATE TABLE Messages (
    MessageID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    SenderID UNIQUEIDENTIFIER NOT NULL,
    ReceiverID UNIQUEIDENTIFIER NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    SentDate TIMESTAMP NOT NULL,
    FOREIGN KEY (SenderID) REFERENCES Users(UserID),
    FOREIGN KEY (ReceiverID) REFERENCES Users(UserID)
);

CREATE TABLE GroupChat (
    GroupID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    GroupName VARCHAR(255) NOT NULL,
	GroupDescription NVARCHAR(500) NOT NULL,
	CreatedBy VARCHAR(100) NOT NULL,
    TextMessage TEXT NOT NULL,
    SenderID UNIQUEIDENTIFIER NOT NULL,
    TimeSent TIMESTAMP NOT NULL,
    FOREIGN KEY (SenderID) REFERENCES Users(UserID)
);

CREATE TABLE GroupAdmins(
	GroupID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (GroupID) REFERENCES GroupChat(GroupID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
)